# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='r_user',
            old_name='profile_picture',
            new_name='profile',
        ),
    ]
