# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20170803_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='rating/media/upload'),
        ),
    ]
