# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20170820_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.R_User'),
        ),
    ]
