# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20170820_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Musicians', 'Musicians'), ('Authors', 'Authors'), ('Actors', 'Actors'), ('Athletes', 'Athletes'), ('Models', 'Models'), ('Hosts', 'Hosts')], max_length=100),
        ),
    ]
