# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:36
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_score_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='title',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='AVG',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='C1',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='C2',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='C3',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='C4',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='C5',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=2),
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
